/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const defineEmits: typeof import('vue')['defineEmits']
  const defineProps: typeof import('vue')['defineProps']
  const defineStore: typeof import('pinia')['defineStore']
  const inject: typeof import('vue')['inject']
  const onMounted: typeof import('vue')['onMounted']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const useAuthStore: typeof import('./stores/index')['useAuthStore']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useSystemContext: typeof import('./composables/useSystemContext')['useSystemContext']
  const useSystemStore: typeof import('./stores/system')['useSystemStore']
  const useUIStore: typeof import('./stores/ui')['useUIStore']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly defineEmits: UnwrapRef<typeof import('vue')['defineEmits']>
    readonly defineProps: UnwrapRef<typeof import('vue')['defineProps']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly useAuthStore: UnwrapRef<typeof import('./stores/index')['useAuthStore']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSystemContext: UnwrapRef<typeof import('./composables/useSystemContext')['useSystemContext']>
    readonly useSystemStore: UnwrapRef<typeof import('./stores/system')['useSystemStore']>
    readonly useUIStore: UnwrapRef<typeof import('./stores/ui')['useUIStore']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
  }
}
